<?php
/**
 * Единый перечень поддерживаемых эмодзи (для inline-панели, стикеров и реакций).
 * Каждый элемент: emoji, keywords (поиск), category (категория для стикеров/фильтров).
 * Сохранён из БД (эталон). При наличии таблицы supported_emojis в БД данные берутся из неё; иначе используется этот массив.
 */

return [
    ['emoji' => '😀', 'keywords' => 'smile happy лицо радость улыбка', 'category' => 'Эмоции'],
    ['emoji' => '😃', 'keywords' => 'smile happy улыбка', 'category' => 'Эмоции'],
    ['emoji' => '😄', 'keywords' => 'smile happy радость', 'category' => 'Эмоции'],
    ['emoji' => '😁', 'keywords' => 'smile grin счастье', 'category' => 'Эмоции'],
    ['emoji' => '😅', 'keywords' => 'sweat холодный пот', 'category' => 'Эмоции'],
    ['emoji' => '😂', 'keywords' => 'laugh tears смех слёзы', 'category' => 'Эмоции'],
    ['emoji' => '🤣', 'keywords' => 'rofl смех', 'category' => 'Эмоции'],
    ['emoji' => '😊', 'keywords' => 'blush улыбка', 'category' => 'Эмоции'],
    ['emoji' => '😇', 'keywords' => 'angel ангел невинность', 'category' => 'Эмоции'],
    ['emoji' => '🙂', 'keywords' => 'smile улыбка', 'category' => 'Эмоции'],
    ['emoji' => '😉', 'keywords' => 'wink подмигивание', 'category' => 'Эмоции'],
    ['emoji' => '😍', 'keywords' => 'love heart глаза сердце', 'category' => 'Эмоции'],
    ['emoji' => '🥰', 'keywords' => 'love in love влюблённость', 'category' => 'Эмоции'],
    ['emoji' => '😘', 'keywords' => 'kiss поцелуй', 'category' => 'Эмоции'],
    ['emoji' => '😗', 'keywords' => 'kiss поцелуй', 'category' => 'Эмоции'],
    ['emoji' => '😙', 'keywords' => 'kiss smile поцелуй', 'category' => 'Эмоции'],
    ['emoji' => '😚', 'keywords' => 'kiss blush поцелуй', 'category' => 'Эмоции'],
    ['emoji' => '😋', 'keywords' => 'yum вкусно', 'category' => 'Эмоции'],
    ['emoji' => '😛', 'keywords' => 'tongue язык', 'category' => 'Эмоции'],
    ['emoji' => '😜', 'keywords' => 'wink tongue язык', 'category' => 'Эмоции'],
    ['emoji' => '🤪', 'keywords' => 'crazy дурачество', 'category' => 'Эмоции'],
    ['emoji' => '😝', 'keywords' => 'tongue язык', 'category' => 'Эмоции'],
    ['emoji' => '🤑', 'keywords' => 'money деньги богатство', 'category' => 'Эмоции'],
    ['emoji' => '🤗', 'keywords' => 'hug объятие', 'category' => 'Эмоции'],
    ['emoji' => '🤭', 'keywords' => 'quiet тихо секрет', 'category' => 'Эмоции'],
    ['emoji' => '🤫', 'keywords' => 'shush тишина', 'category' => 'Эмоции'],
    ['emoji' => '🤔', 'keywords' => 'think думать размышление', 'category' => 'Эмоции'],
    ['emoji' => '😐', 'keywords' => 'neutral нейтрально', 'category' => 'Эмоции'],
    ['emoji' => '😑', 'keywords' => 'expressionless без эмоций', 'category' => 'Эмоции'],
    ['emoji' => '😶', 'keywords' => 'silent без слов', 'category' => 'Эмоции'],
    ['emoji' => '😏', 'keywords' => 'smirk усмешка', 'category' => 'Эмоции'],
    ['emoji' => '😒', 'keywords' => 'unamused недовольство', 'category' => 'Эмоции'],
    ['emoji' => '🙄', 'keywords' => 'roll eyes закатывание глаз', 'category' => 'Эмоции'],
    ['emoji' => '😬', 'keywords' => 'grimace гримаса', 'category' => 'Эмоции'],
    ['emoji' => '🤥', 'keywords' => 'lie ложь', 'category' => 'Эмоции'],
    ['emoji' => '😌', 'keywords' => 'relief облегчение', 'category' => 'Эмоции'],
    ['emoji' => '😔', 'keywords' => 'sad грусть', 'category' => 'Эмоции'],
    ['emoji' => '😪', 'keywords' => 'sleepy сонный', 'category' => 'Эмоции'],
    ['emoji' => '🤤', 'keywords' => 'drool слюни', 'category' => 'Эмоции'],
    ['emoji' => '😴', 'keywords' => 'sleep сон', 'category' => 'Эмоции'],
    ['emoji' => '😷', 'keywords' => 'mask маска болезнь', 'category' => 'Эмоции'],
    ['emoji' => '🤒', 'keywords' => 'sick болезнь температура', 'category' => 'Эмоции'],
    ['emoji' => '🤕', 'keywords' => 'hurt травма', 'category' => 'Эмоции'],
    ['emoji' => '🤢', 'keywords' => 'nauseous тошнота', 'category' => 'Эмоции'],
    ['emoji' => '🤮', 'keywords' => 'vomit рвота', 'category' => 'Эмоции'],
    ['emoji' => '🤧', 'keywords' => 'sneeze чихание', 'category' => 'Эмоции'],
    ['emoji' => '🥵', 'keywords' => 'hot жарко', 'category' => 'Эмоции'],
    ['emoji' => '🥶', 'keywords' => 'cold холодно', 'category' => 'Эмоции'],
    ['emoji' => '🥴', 'keywords' => 'woozy головокружение', 'category' => 'Эмоции'],
    ['emoji' => '😵', 'keywords' => 'dizzy головокружение', 'category' => 'Эмоции'],
    ['emoji' => '🤯', 'keywords' => 'mind blown взрыв мозга', 'category' => 'Эмоции'],
    ['emoji' => '🤠', 'keywords' => 'cowboy ковбой', 'category' => 'Эмоции'],
    ['emoji' => '🥳', 'keywords' => 'party праздник', 'category' => 'Эмоции'],
    ['emoji' => '😎', 'keywords' => 'cool круто очки', 'category' => 'Эмоции'],
    ['emoji' => '🤓', 'keywords' => 'nerd ботаник', 'category' => 'Эмоции'],
    ['emoji' => '🧐', 'keywords' => 'monocle монокль', 'category' => 'Эмоции'],
    ['emoji' => '😕', 'keywords' => 'confused смущение', 'category' => 'Эмоции'],
    ['emoji' => '😟', 'keywords' => 'worried беспокойство', 'category' => 'Эмоции'],
    ['emoji' => '🙁', 'keywords' => 'sad грусть', 'category' => 'Эмоции'],
    ['emoji' => '😮', 'keywords' => 'surprise удивление', 'category' => 'Эмоции'],
    ['emoji' => '😯', 'keywords' => 'hushed тихий', 'category' => 'Эмоции'],
    ['emoji' => '😲', 'keywords' => 'astonished изумление', 'category' => 'Эмоции'],
    ['emoji' => '😳', 'keywords' => 'flushed смущение', 'category' => 'Эмоции'],
    ['emoji' => '🥺', 'keywords' => 'pleading просьба', 'category' => 'Эмоции'],
    ['emoji' => '😦', 'keywords' => 'frown грусть', 'category' => 'Эмоции'],
    ['emoji' => '😧', 'keywords' => 'anguish страдание', 'category' => 'Эмоции'],
    ['emoji' => '😨', 'keywords' => 'fear страх', 'category' => 'Эмоции'],
    ['emoji' => '😰', 'keywords' => 'anxious тревога', 'category' => 'Эмоции'],
    ['emoji' => '😥', 'keywords' => 'sad relief грусть', 'category' => 'Эмоции'],
    ['emoji' => '😢', 'keywords' => 'cry плач', 'category' => 'Эмоции'],
    ['emoji' => '😭', 'keywords' => 'sob слёзы', 'category' => 'Эмоции'],
    ['emoji' => '😱', 'keywords' => 'scream крик', 'category' => 'Эмоции'],
    ['emoji' => '😖', 'keywords' => 'confounded смятение', 'category' => 'Эмоции'],
    ['emoji' => '😣', 'keywords' => 'persevere упорство', 'category' => 'Эмоции'],
    ['emoji' => '😞', 'keywords' => 'disappointed разочарование', 'category' => 'Эмоции'],
    ['emoji' => '😓', 'keywords' => 'sweat пот', 'category' => 'Эмоции'],
    ['emoji' => '😩', 'keywords' => 'weary усталость', 'category' => 'Эмоции'],
    ['emoji' => '😫', 'keywords' => 'tired усталость', 'category' => 'Эмоции'],
    ['emoji' => '🥱', 'keywords' => 'yawn зевота', 'category' => 'Эмоции'],
    ['emoji' => '😤', 'keywords' => 'frustrated фрустрация', 'category' => 'Эмоции'],
    ['emoji' => '😠', 'keywords' => 'mad злость', 'category' => 'Эмоции'],
    ['emoji' => '😡', 'keywords' => 'angry злость', 'category' => 'Эмоции'],
    ['emoji' => '🤬', 'keywords' => 'swear ругательство', 'category' => 'Эмоции'],
    ['emoji' => '😈', 'keywords' => 'devil дьявол', 'category' => 'Эмоции'],
    ['emoji' => '💀', 'keywords' => 'skull череп смерть', 'category' => 'Эмоции'],
    ['emoji' => '☠️', 'keywords' => 'skull death смерть', 'category' => 'Эмоции'],
    ['emoji' => '💩', 'keywords' => 'poop какашка', 'category' => 'Эмоции'],
    ['emoji' => '🤡', 'keywords' => 'clown клоун', 'category' => 'Эмоции'],
    ['emoji' => '👻', 'keywords' => 'ghost призрак', 'category' => 'Эмоции'],
    ['emoji' => '👍', 'keywords' => 'thumbs up одобрение ок', 'category' => 'Жесты'],
    ['emoji' => '👎', 'keywords' => 'thumbs down неодобрение', 'category' => 'Жесты'],
    ['emoji' => '☝️', 'keywords' => 'point один', 'category' => 'Жесты'],
    ['emoji' => '💪', 'keywords' => 'muscle сила', 'category' => 'Жесты'],
    ['emoji' => '✊', 'keywords' => 'fist кулак', 'category' => 'Жесты'],
    ['emoji' => '👊', 'keywords' => 'punch кулак', 'category' => 'Жесты'],
    ['emoji' => '🤛', 'keywords' => 'fist left левый кулак', 'category' => 'Жесты'],
    ['emoji' => '🤜', 'keywords' => 'fist right правый кулак', 'category' => 'Жесты'],
    ['emoji' => '👏', 'keywords' => 'clap аплодисменты', 'category' => 'Жесты'],
    ['emoji' => '🙌', 'keywords' => 'raise hands руки вверх', 'category' => 'Жесты'],
    ['emoji' => '👐', 'keywords' => 'open hands открытые руки', 'category' => 'Жесты'],
    ['emoji' => '🤲', 'keywords' => 'palms up руки', 'category' => 'Жесты'],
    ['emoji' => '🤝', 'keywords' => 'handshake рукопожатие', 'category' => 'Жесты'],
    ['emoji' => '🙏', 'keywords' => 'pray пожалуйста спасибо', 'category' => 'Жесты'],
    ['emoji' => '✌️', 'keywords' => 'peace победа', 'category' => 'Жесты'],
    ['emoji' => '🤞', 'keywords' => 'fingers crossed удача', 'category' => 'Жесты'],
    ['emoji' => '🤟', 'keywords' => 'love you люблю', 'category' => 'Жесты'],
    ['emoji' => '🤘', 'keywords' => 'rock рок', 'category' => 'Жесты'],
    ['emoji' => '🤙', 'keywords' => 'call позвонить', 'category' => 'Жесты'],
    ['emoji' => '👌', 'keywords' => 'ok ок', 'category' => 'Жесты'],
    ['emoji' => '🤏', 'keywords' => 'small маленький', 'category' => 'Жесты'],
    ['emoji' => '👈', 'keywords' => 'point left влево', 'category' => 'Жесты'],
    ['emoji' => '👉', 'keywords' => 'point right вправо', 'category' => 'Жесты'],
    ['emoji' => '👆', 'keywords' => 'point up вверх', 'category' => 'Жесты'],
    ['emoji' => '👇', 'keywords' => 'point down вниз', 'category' => 'Жесты'],
    ['emoji' => '❤️', 'keywords' => 'heart love сердце любовь', 'category' => 'Сердечки'],
    ['emoji' => '🧡', 'keywords' => 'orange heart оранжевое сердце', 'category' => 'Сердечки'],
    ['emoji' => '💛', 'keywords' => 'yellow heart жёлтое сердце', 'category' => 'Сердечки'],
    ['emoji' => '💚', 'keywords' => 'green heart зелёное сердце', 'category' => 'Сердечки'],
    ['emoji' => '💙', 'keywords' => 'blue heart синее сердце', 'category' => 'Сердечки'],
    ['emoji' => '💜', 'keywords' => 'purple heart фиолетовое сердце', 'category' => 'Сердечки'],
    ['emoji' => '🖤', 'keywords' => 'black heart чёрное сердце', 'category' => 'Сердечки'],
    ['emoji' => '🤍', 'keywords' => 'white heart белое сердце', 'category' => 'Сердечки'],
    ['emoji' => '🤎', 'keywords' => 'brown heart коричневое сердце', 'category' => 'Сердечки'],
    ['emoji' => '💔', 'keywords' => 'broken heart разбитое сердце', 'category' => 'Сердечки'],
    ['emoji' => '❣️', 'keywords' => 'heart exclamation сердце', 'category' => 'Сердечки'],
    ['emoji' => '💕', 'keywords' => 'two hearts два сердца', 'category' => 'Сердечки'],
    ['emoji' => '💞', 'keywords' => 'revolving hearts сердца', 'category' => 'Сердечки'],
    ['emoji' => '💓', 'keywords' => 'beating heart сердцебиение', 'category' => 'Сердечки'],
    ['emoji' => '💗', 'keywords' => 'growing heart растущее сердце', 'category' => 'Сердечки'],
    ['emoji' => '💖', 'keywords' => 'sparkling heart сердце', 'category' => 'Сердечки'],
    ['emoji' => '💘', 'keywords' => 'heart arrow сердце стрела', 'category' => 'Сердечки'],
    ['emoji' => '💝', 'keywords' => 'heart ribbon сердце лента', 'category' => 'Сердечки'],
    ['emoji' => '💟', 'keywords' => 'heart decoration сердце', 'category' => 'Сердечки'],
    ['emoji' => '☮️', 'keywords' => 'peace мир', 'category' => 'Символы'],
    ['emoji' => '✝️', 'keywords' => 'cross крест', 'category' => 'Символы'],
    ['emoji' => '☦️', 'keywords' => 'orthodox крест', 'category' => 'Символы'],
    ['emoji' => '☯️', 'keywords' => 'yin yang инь янь', 'category' => 'Символы'],
    ['emoji' => '☪️', 'keywords' => 'star crescent полумесяц', 'category' => 'Символы'],
    ['emoji' => '🕉️', 'keywords' => 'om ом', 'category' => 'Символы'],
    ['emoji' => '☸️', 'keywords' => 'wheel дхарма', 'category' => 'Символы'],
    ['emoji' => '✡️', 'keywords' => 'star david звезда', 'category' => 'Символы'],
    ['emoji' => '🔯', 'keywords' => 'star шестиконечная', 'category' => 'Символы'],
    ['emoji' => '🕎', 'keywords' => 'menorah менора', 'category' => 'Символы'],
    ['emoji' => '🛐', 'keywords' => 'place worship место', 'category' => 'Символы'],
    ['emoji' => '⛎', 'keywords' => 'ophiuchus змееносец', 'category' => 'Символы'],
    ['emoji' => '♈', 'keywords' => 'aries овен', 'category' => 'Символы'],
    ['emoji' => '♉', 'keywords' => 'taurus телец', 'category' => 'Символы'],
    ['emoji' => '♊', 'keywords' => 'gemini близнецы', 'category' => 'Символы'],
    ['emoji' => '♋', 'keywords' => 'cancer рак', 'category' => 'Символы'],
    ['emoji' => '♌', 'keywords' => 'leo лев', 'category' => 'Символы'],
    ['emoji' => '♍', 'keywords' => 'virgo дева', 'category' => 'Символы'],
    ['emoji' => '♎', 'keywords' => 'libra весы', 'category' => 'Символы'],
    ['emoji' => '♏', 'keywords' => 'scorpio скорпион', 'category' => 'Символы'],
    ['emoji' => '♐', 'keywords' => 'sagittarius стрелец', 'category' => 'Символы'],
    ['emoji' => '♑', 'keywords' => 'capricorn козерог', 'category' => 'Символы'],
    ['emoji' => '♒', 'keywords' => 'aquarius водолей', 'category' => 'Символы'],
    ['emoji' => '♓', 'keywords' => 'pisces рыбы', 'category' => 'Символы'],
    ['emoji' => '🆔', 'keywords' => 'id идентификация', 'category' => 'Символы'],
    ['emoji' => '⚛️', 'keywords' => 'atom атом', 'category' => 'Символы'],
    ['emoji' => '🉑', 'keywords' => 'accept принять', 'category' => 'Символы'],
    ['emoji' => '🈶', 'keywords' => 'ideograph есть', 'category' => 'Символы'],
    ['emoji' => '🈚', 'keywords' => 'ideograph нет', 'category' => 'Символы'],
    ['emoji' => '🈸', 'keywords' => 'ideograph заявление', 'category' => 'Символы'],
    ['emoji' => '🈺', 'keywords' => 'ideograph открыто', 'category' => 'Символы'],
    ['emoji' => '🈷️', 'keywords' => 'ideograph месяц', 'category' => 'Символы'],
    ['emoji' => '✴️', 'keywords' => 'star звезда', 'category' => 'Символы'],
    ['emoji' => '🆚', 'keywords' => 'vs против', 'category' => 'Символы'],
    ['emoji' => '💮', 'keywords' => 'flower цветок', 'category' => 'Символы'],
    ['emoji' => '🉐', 'keywords' => 'ideograph выгода', 'category' => 'Символы'],
    ['emoji' => '㊙️', 'keywords' => 'secret секрет', 'category' => 'Символы'],
    ['emoji' => '㊗️', 'keywords' => 'congratulations поздравление', 'category' => 'Символы'],
    ['emoji' => '🈴', 'keywords' => 'ideograph сдать', 'category' => 'Символы'],
    ['emoji' => '🈵', 'keywords' => 'ideograph полный', 'category' => 'Символы'],
    ['emoji' => '🈹', 'keywords' => 'ideograph скидка', 'category' => 'Символы'],
    ['emoji' => '🈲', 'keywords' => 'ideograph запрещено', 'category' => 'Символы'],
    ['emoji' => '🅰️', 'keywords' => 'a буква', 'category' => 'Символы'],
    ['emoji' => '🅱️', 'keywords' => 'b буква', 'category' => 'Символы'],
    ['emoji' => '🆎', 'keywords' => 'ab кровь', 'category' => 'Символы'],
    ['emoji' => '🆑', 'keywords' => 'cl очистить', 'category' => 'Символы'],
    ['emoji' => '🅾️', 'keywords' => 'o буква', 'category' => 'Символы'],
    ['emoji' => '🆘', 'keywords' => 'sos помощь', 'category' => 'Символы'],
    ['emoji' => '🛑', 'keywords' => 'stop стоп', 'category' => 'Символы'],
    ['emoji' => '⛔', 'keywords' => 'no entry въезд запрещён', 'category' => 'Символы'],
    ['emoji' => '📛', 'keywords' => 'name badge бейдж', 'category' => 'Символы'],
    ['emoji' => '🚫', 'keywords' => 'prohibited запрещено', 'category' => 'Символы'],
    ['emoji' => '💯', 'keywords' => '100 сто идеально', 'category' => 'Символы'],
    ['emoji' => '💢', 'keywords' => 'anger злость', 'category' => 'Символы'],
    ['emoji' => '♨️', 'keywords' => 'hot springs горячие источники', 'category' => 'Символы'],
    ['emoji' => '🚷', 'keywords' => 'no pedestrians пешеходы', 'category' => 'Символы'],
    ['emoji' => '🚯', 'keywords' => 'no littering мусор', 'category' => 'Символы'],
    ['emoji' => '🚳', 'keywords' => 'no bicycles велосипеды', 'category' => 'Символы'],
    ['emoji' => '🚱', 'keywords' => 'non-drinkable вода', 'category' => 'Символы'],
    ['emoji' => '🔞', 'keywords' => '18 возраст', 'category' => 'Символы'],
    ['emoji' => '📵', 'keywords' => 'no phones телефоны', 'category' => 'Символы'],
    ['emoji' => '🚭', 'keywords' => 'no smoking курение', 'category' => 'Символы'],
    ['emoji' => '⭕', 'keywords' => 'circle круг ок', 'category' => 'Символы'],
    ['emoji' => '❌', 'keywords' => 'cross no нет ошибка', 'category' => 'Символы'],
    ['emoji' => '❕', 'keywords' => 'exclamation восклицание', 'category' => 'Символы'],
    ['emoji' => '❗', 'keywords' => 'exclamation восклицание', 'category' => 'Символы'],
    ['emoji' => '‼️', 'keywords' => 'double exclamation', 'category' => 'Символы'],
    ['emoji' => '⁉️', 'keywords' => 'exclamation question', 'category' => 'Символы'],
    ['emoji' => '❔', 'keywords' => 'question вопрос', 'category' => 'Символы'],
    ['emoji' => '❓', 'keywords' => 'question вопрос', 'category' => 'Символы'],
    ['emoji' => '🔅', 'keywords' => 'dim тусклый', 'category' => 'Символы'],
    ['emoji' => '🔆', 'keywords' => 'bright яркий', 'category' => 'Символы'],
    ['emoji' => '〽️', 'keywords' => 'part alternation', 'category' => 'Символы'],
    ['emoji' => '☢️', 'keywords' => 'radioactive радиация', 'category' => 'Символы'],
    ['emoji' => '☣️', 'keywords' => 'bio опасность', 'category' => 'Символы'],
    ['emoji' => '⚠️', 'keywords' => 'warning внимание', 'category' => 'Символы'],
    ['emoji' => '🚸', 'keywords' => 'children дети', 'category' => 'Символы'],
    ['emoji' => '🔱', 'keywords' => 'trident трезубец', 'category' => 'Символы'],
    ['emoji' => '⚜️', 'keywords' => 'fleur-de-lis', 'category' => 'Символы'],
    ['emoji' => '🔰', 'keywords' => 'beginner начинающий', 'category' => 'Символы'],
    ['emoji' => '♻️', 'keywords' => 'recycle переработка', 'category' => 'Символы'],
    ['emoji' => '✅', 'keywords' => 'check галочка да', 'category' => 'Символы'],
    ['emoji' => '🈯', 'keywords' => 'ideograph указать', 'category' => 'Символы'],
    ['emoji' => '💹', 'keywords' => 'chart рост', 'category' => 'Символы'],
    ['emoji' => '❇️', 'keywords' => 'sparkle искра', 'category' => 'Символы'],
    ['emoji' => '✳️', 'keywords' => 'asterisk звёздочка', 'category' => 'Символы'],
    ['emoji' => '❎', 'keywords' => 'cross mark крестик', 'category' => 'Символы'],
    ['emoji' => '🌐', 'keywords' => 'globe глобус мир', 'category' => 'Символы'],
    ['emoji' => 'Ⓜ️', 'keywords' => 'm буква', 'category' => 'Символы'],
    ['emoji' => '💠', 'keywords' => 'diamond diamond', 'category' => 'Символы'],
    ['emoji' => '🌀', 'keywords' => 'cyclone циклон', 'category' => 'Символы'],
    ['emoji' => '💤', 'keywords' => 'zzz сон', 'category' => 'Символы'],
    ['emoji' => '📴', 'keywords' => 'phone off телефон выключен', 'category' => 'Символы'],
    ['emoji' => '📳', 'keywords' => 'vibration вибрация', 'category' => 'Символы'],
    ['emoji' => '🏧', 'keywords' => 'atm банкомат', 'category' => 'Символы'],
    ['emoji' => '💲', 'keywords' => 'dollar доллар', 'category' => 'Символы'],
    ['emoji' => '💱', 'keywords' => 'exchange обмен', 'category' => 'Символы'],
    ['emoji' => '🅿️', 'keywords' => 'parking парковка', 'category' => 'Символы'],
    ['emoji' => '🈳', 'keywords' => 'ideograph свободно', 'category' => 'Символы'],
    ['emoji' => '🈂️', 'keywords' => 'ideograph сервис', 'category' => 'Символы'],
    ['emoji' => '🛂', 'keywords' => 'passport контроль', 'category' => 'Символы'],
    ['emoji' => '🛃', 'keywords' => 'customs таможня', 'category' => 'Символы'],
    ['emoji' => '🛄', 'keywords' => 'baggage багаж', 'category' => 'Символы'],
    ['emoji' => '🛅', 'keywords' => 'left luggage багаж', 'category' => 'Символы'],
    ['emoji' => '🚮', 'keywords' => 'litter мусор', 'category' => 'Символы'],
    ['emoji' => '🚾', 'keywords' => 'wc туалет', 'category' => 'Символы'],
    ['emoji' => '🚻', 'keywords' => 'toilet туалет', 'category' => 'Символы'],
    ['emoji' => '🚹', 'keywords' => 'men мужчины', 'category' => 'Символы'],
    ['emoji' => '🚺', 'keywords' => 'women женщины', 'category' => 'Символы'],
    ['emoji' => '♿', 'keywords' => 'wheelchair доступность', 'category' => 'Символы'],
    ['emoji' => '🚼', 'keywords' => 'baby дети', 'category' => 'Символы'],
    ['emoji' => '⚧️', 'keywords' => 'transgender', 'category' => 'Символы'],
    ['emoji' => '🎦', 'keywords' => 'cinema кино', 'category' => 'Символы'],
    ['emoji' => '📶', 'keywords' => 'signal сигнал', 'category' => 'Символы'],
    ['emoji' => '🈁', 'keywords' => 'ideograph здесь', 'category' => 'Символы'],
    ['emoji' => '🔣', 'keywords' => 'symbols символы', 'category' => 'Символы'],
    ['emoji' => 'ℹ️', 'keywords' => 'info информация', 'category' => 'Символы'],
    ['emoji' => '🔤', 'keywords' => 'abc латиница', 'category' => 'Символы'],
    ['emoji' => '🔡', 'keywords' => 'abcd буквы', 'category' => 'Символы'],
    ['emoji' => '🔠', 'keywords' => 'abcd заглавные', 'category' => 'Символы'],
    ['emoji' => '🆖', 'keywords' => 'ng не хорошо', 'category' => 'Символы'],
    ['emoji' => '🆗', 'keywords' => 'ok ок', 'category' => 'Символы'],
    ['emoji' => '🆙', 'keywords' => 'up вверх', 'category' => 'Символы'],
    ['emoji' => '🆒', 'keywords' => 'cool круто', 'category' => 'Символы'],
    ['emoji' => '🆕', 'keywords' => 'new новое', 'category' => 'Символы'],
    ['emoji' => '🆓', 'keywords' => 'free бесплатно', 'category' => 'Символы'],
    ['emoji' => '0️⃣', 'keywords' => 'zero ноль', 'category' => 'Символы'],
    ['emoji' => '1️⃣', 'keywords' => 'one один', 'category' => 'Символы'],
    ['emoji' => '2️⃣', 'keywords' => 'two два', 'category' => 'Символы'],
    ['emoji' => '3️⃣', 'keywords' => 'three три', 'category' => 'Символы'],
    ['emoji' => '4️⃣', 'keywords' => 'four четыре', 'category' => 'Символы'],
    ['emoji' => '5️⃣', 'keywords' => 'five пять', 'category' => 'Символы'],
    ['emoji' => '6️⃣', 'keywords' => 'six шесть', 'category' => 'Символы'],
    ['emoji' => '7️⃣', 'keywords' => 'seven семь', 'category' => 'Символы'],
    ['emoji' => '8️⃣', 'keywords' => 'eight восемь', 'category' => 'Символы'],
    ['emoji' => '9️⃣', 'keywords' => 'nine девять', 'category' => 'Символы'],
    ['emoji' => '🔟', 'keywords' => 'ten десять', 'category' => 'Символы'],
    ['emoji' => '🔢', 'keywords' => 'numbers цифры', 'category' => 'Символы'],
    ['emoji' => '#️⃣', 'keywords' => 'hash решётка', 'category' => 'Символы'],
    ['emoji' => '*️⃣', 'keywords' => 'asterisk звёздочка', 'category' => 'Символы'],
    ['emoji' => '⏏️', 'keywords' => 'eject извлечь', 'category' => 'Символы'],
    ['emoji' => '▶️', 'keywords' => 'play играть', 'category' => 'Символы'],
    ['emoji' => '⏸️', 'keywords' => 'pause пауза', 'category' => 'Символы'],
    ['emoji' => '⏯️', 'keywords' => 'play pause', 'category' => 'Символы'],
    ['emoji' => '⏹️', 'keywords' => 'stop стоп', 'category' => 'Символы'],
    ['emoji' => '⏺️', 'keywords' => 'record запись', 'category' => 'Символы'],
    ['emoji' => '⏭️', 'keywords' => 'next следующий', 'category' => 'Символы'],
    ['emoji' => '⏮️', 'keywords' => 'previous предыдущий', 'category' => 'Символы'],
    ['emoji' => '⏩', 'keywords' => 'fast forward', 'category' => 'Символы'],
    ['emoji' => '⏪', 'keywords' => 'rewind назад', 'category' => 'Символы'],
    ['emoji' => '⏫', 'keywords' => 'up вверх', 'category' => 'Символы'],
    ['emoji' => '⏬', 'keywords' => 'down вниз', 'category' => 'Символы'],
    ['emoji' => '◀️', 'keywords' => 'reverse назад', 'category' => 'Символы'],
    ['emoji' => '🔼', 'keywords' => 'up вверх', 'category' => 'Символы'],
    ['emoji' => '🔽', 'keywords' => 'down вниз', 'category' => 'Символы'],
    ['emoji' => '➡️', 'keywords' => 'right вправо', 'category' => 'Символы'],
    ['emoji' => '⬅️', 'keywords' => 'left влево', 'category' => 'Символы'],
    ['emoji' => '⬆️', 'keywords' => 'up вверх', 'category' => 'Символы'],
    ['emoji' => '⬇️', 'keywords' => 'down вниз', 'category' => 'Символы'],
    ['emoji' => '↗️', 'keywords' => 'up right', 'category' => 'Символы'],
    ['emoji' => '↘️', 'keywords' => 'down right', 'category' => 'Символы'],
    ['emoji' => '↙️', 'keywords' => 'down left', 'category' => 'Символы'],
    ['emoji' => '↖️', 'keywords' => 'up left', 'category' => 'Символы'],
    ['emoji' => '↕️', 'keywords' => 'vertical вертикаль', 'category' => 'Символы'],
    ['emoji' => '↔️', 'keywords' => 'horizontal горизонталь', 'category' => 'Символы'],
    ['emoji' => '↪️', 'keywords' => 'return return', 'category' => 'Символы'],
    ['emoji' => '↩️', 'keywords' => 'return обратно', 'category' => 'Символы'],
    ['emoji' => '⤴️', 'keywords' => 'arrow вверх', 'category' => 'Символы'],
    ['emoji' => '⤵️', 'keywords' => 'arrow вниз', 'category' => 'Символы'],
    ['emoji' => '🔀', 'keywords' => 'shuffle перемешать', 'category' => 'Символы'],
    ['emoji' => '🔁', 'keywords' => 'repeat повторить', 'category' => 'Символы'],
    ['emoji' => '🔂', 'keywords' => 'repeat one один', 'category' => 'Символы'],
    ['emoji' => '🔄', 'keywords' => 'arrows обновить', 'category' => 'Символы'],
    ['emoji' => '🔃', 'keywords' => 'arrows clockwise', 'category' => 'Символы'],
    ['emoji' => '🎵', 'keywords' => 'music музыка', 'category' => 'Символы'],
    ['emoji' => '🎶', 'keywords' => 'music ноты', 'category' => 'Символы'],
    ['emoji' => '➕', 'keywords' => 'plus плюс', 'category' => 'Символы'],
    ['emoji' => '➖', 'keywords' => 'minus минус', 'category' => 'Символы'],
    ['emoji' => '➗', 'keywords' => 'divide деление', 'category' => 'Символы'],
    ['emoji' => '✖️', 'keywords' => 'multiply умножение', 'category' => 'Символы'],
    ['emoji' => '♾️', 'keywords' => 'infinity бесконечность', 'category' => 'Символы'],
    ['emoji' => '™️', 'keywords' => 'tm торговая марка', 'category' => 'Символы'],
    ['emoji' => '©️', 'keywords' => 'copyright копирайт', 'category' => 'Символы'],
    ['emoji' => '®️', 'keywords' => 'registered зарегистрировано', 'category' => 'Символы'],
    ['emoji' => '🤌', 'keywords' => 'pinch щепотка', 'category' => 'Hidden'],
    ['emoji' => '🛗', 'keywords' => 'elevator лифт', 'category' => 'Hidden'],
    // ——— Природа (дополнение) ———
    ['emoji' => '🌟', 'keywords' => 'star glowing звезда сияние', 'category' => 'Природа'],
    ['emoji' => '⭐', 'keywords' => 'star звезда', 'category' => 'Природа'],
    ['emoji' => '✨', 'keywords' => 'sparkles искры блеск', 'category' => 'Природа'],
    ['emoji' => '🔥', 'keywords' => 'fire огонь жар круто', 'category' => 'Природа'],
    ['emoji' => '❄️', 'keywords' => 'snowflake снежинка холод', 'category' => 'Природа'],
    ['emoji' => '🌈', 'keywords' => 'rainbow радуга', 'category' => 'Природа'],
    ['emoji' => '☀️', 'keywords' => 'sun солнце', 'category' => 'Природа'],
    ['emoji' => '🌙', 'keywords' => 'moon луна ночь', 'category' => 'Природа'],
    ['emoji' => '🌺', 'keywords' => 'hibiscus гибискус цветок', 'category' => 'Природа'],
    ['emoji' => '🌸', 'keywords' => 'cherry blossom сакура цветок', 'category' => 'Природа'],
    ['emoji' => '🌻', 'keywords' => 'sunflower подсолнух', 'category' => 'Природа'],
    ['emoji' => '🌹', 'keywords' => 'rose роза цветок', 'category' => 'Природа'],
    ['emoji' => '🍀', 'keywords' => 'clover клевер удача', 'category' => 'Природа'],
    ['emoji' => '🌴', 'keywords' => 'palm пальма дерево', 'category' => 'Природа'],
    ['emoji' => '🌵', 'keywords' => 'cactus кактус', 'category' => 'Природа'],
    ['emoji' => '🦋', 'keywords' => 'butterfly бабочка', 'category' => 'Природа'],
    ['emoji' => '🐝', 'keywords' => 'bee пчела', 'category' => 'Природа'],
    ['emoji' => '🌊', 'keywords' => 'wave волна море', 'category' => 'Природа'],
    ['emoji' => '🍃', 'keywords' => 'leaf лист природа', 'category' => 'Природа'],
    ['emoji' => '🍂', 'keywords' => 'fallen leaf осень лист', 'category' => 'Природа'],
    // ——— Животные ———
    ['emoji' => '🐶', 'keywords' => 'dog собака пёс', 'category' => 'Животные'],
    ['emoji' => '🐱', 'keywords' => 'cat кот кошка', 'category' => 'Животные'],
    ['emoji' => '🐭', 'keywords' => 'mouse мышь', 'category' => 'Животные'],
    ['emoji' => '🐹', 'keywords' => 'hamster хомяк', 'category' => 'Животные'],
    ['emoji' => '🐰', 'keywords' => 'rabbit заяц кролик', 'category' => 'Животные'],
    ['emoji' => '🦊', 'keywords' => 'fox лиса', 'category' => 'Животные'],
    ['emoji' => '🐻', 'keywords' => 'bear медведь', 'category' => 'Животные'],
    ['emoji' => '🐼', 'keywords' => 'panda панда', 'category' => 'Животные'],
    ['emoji' => '🐨', 'keywords' => 'koala коала', 'category' => 'Животные'],
    ['emoji' => '🐯', 'keywords' => 'tiger тигр', 'category' => 'Животные'],
    ['emoji' => '🦁', 'keywords' => 'lion лев', 'category' => 'Животные'],
    ['emoji' => '🐮', 'keywords' => 'cow корова', 'category' => 'Животные'],
    ['emoji' => '🐷', 'keywords' => 'pig свинья', 'category' => 'Животные'],
    ['emoji' => '🐸', 'keywords' => 'frog лягушка', 'category' => 'Животные'],
    ['emoji' => '🐵', 'keywords' => 'monkey обезьяна', 'category' => 'Животные'],
    ['emoji' => '🙈', 'keywords' => 'see no evil monkey обезьяна глаза не вижу', 'category' => 'Животные'],
    ['emoji' => '🙉', 'keywords' => 'hear no evil monkey обезьяна уши не слышу', 'category' => 'Животные'],
    ['emoji' => '🙊', 'keywords' => 'speak no evil monkey обезьяна рот не говорю', 'category' => 'Животные'],
    ['emoji' => '🐔', 'keywords' => 'chicken курица петух', 'category' => 'Животные'],
    ['emoji' => '🐧', 'keywords' => 'penguin пингвин', 'category' => 'Животные'],
    ['emoji' => '🐦', 'keywords' => 'bird птица', 'category' => 'Животные'],
    ['emoji' => '🦄', 'keywords' => 'unicorn единорог', 'category' => 'Животные'],
    ['emoji' => '🐲', 'keywords' => 'dragon дракон', 'category' => 'Животные'],
    // ——— Еда и напитки ———
    ['emoji' => '🍕', 'keywords' => 'pizza пицца', 'category' => 'Еда и напитки'],
    ['emoji' => '🍔', 'keywords' => 'hamburger бургер гамбургер', 'category' => 'Еда и напитки'],
    ['emoji' => '🍟', 'keywords' => 'fries картошка фри', 'category' => 'Еда и напитки'],
    ['emoji' => '☕', 'keywords' => 'coffee кофе', 'category' => 'Еда и напитки'],
    ['emoji' => '🍺', 'keywords' => 'beer пиво', 'category' => 'Еда и напитки'],
    ['emoji' => '🍷', 'keywords' => 'wine вино', 'category' => 'Еда и напитки'],
    ['emoji' => '🍎', 'keywords' => 'apple яблоко', 'category' => 'Еда и напитки'],
    ['emoji' => '🍊', 'keywords' => 'orange апельсин', 'category' => 'Еда и напитки'],
    ['emoji' => '🍋', 'keywords' => 'lemon лимон', 'category' => 'Еда и напитки'],
    ['emoji' => '🍇', 'keywords' => 'grapes виноград', 'category' => 'Еда и напитки'],
    ['emoji' => '🍰', 'keywords' => 'cake торт праздник', 'category' => 'Еда и напитки'],
    ['emoji' => '🎂', 'keywords' => 'birthday cake день рождения торт', 'category' => 'Еда и напитки'],
    ['emoji' => '🍩', 'keywords' => 'donut пончик', 'category' => 'Еда и напитки'],
    ['emoji' => '🍪', 'keywords' => 'cookie печенье', 'category' => 'Еда и напитки'],
    ['emoji' => '🥤', 'keywords' => 'cup стакан напиток', 'category' => 'Еда и напитки'],
    // ——— Активность и спорт ———
    ['emoji' => '⚽', 'keywords' => 'soccer футбол мяч', 'category' => 'Активность'],
    ['emoji' => '🏀', 'keywords' => 'basketball баскетбол', 'category' => 'Активность'],
    ['emoji' => '🎮', 'keywords' => 'game игра гейм', 'category' => 'Активность'],
    ['emoji' => '🎸', 'keywords' => 'guitar гитара музыка', 'category' => 'Активность'],
    ['emoji' => '🎬', 'keywords' => 'movie кино фильм', 'category' => 'Активность'],
    ['emoji' => '🎯', 'keywords' => 'target цель мишень', 'category' => 'Активность'],
    ['emoji' => '🎁', 'keywords' => 'gift подарок', 'category' => 'Активность'],
    ['emoji' => '🎄', 'keywords' => 'christmas tree ёлка новый год', 'category' => 'Активность'],
    ['emoji' => '🎉', 'keywords' => 'party праздник ура', 'category' => 'Активность'],
    ['emoji' => '🎊', 'keywords' => 'confetti конфетти праздник', 'category' => 'Активность'],
    ['emoji' => '🏆', 'keywords' => 'trophy кубок победа', 'category' => 'Активность'],
    ['emoji' => '🥇', 'keywords' => 'medal gold золото первое место', 'category' => 'Активность'],
    // ——— Предметы и техника ———
    ['emoji' => '📱', 'keywords' => 'phone телефон мобильный', 'category' => 'Предметы'],
    ['emoji' => '💻', 'keywords' => 'computer компьютер ноутбук', 'category' => 'Предметы'],
    ['emoji' => '⌚', 'keywords' => 'watch часы время', 'category' => 'Предметы'],
    ['emoji' => '🔔', 'keywords' => 'bell звонок уведомление', 'category' => 'Предметы'],
    ['emoji' => '💡', 'keywords' => 'light bulb лампочка идея', 'category' => 'Предметы'],
    ['emoji' => '🔒', 'keywords' => 'lock замок закрыто', 'category' => 'Предметы'],
    ['emoji' => '🔑', 'keywords' => 'key ключ', 'category' => 'Предметы'],
    ['emoji' => '✉️', 'keywords' => 'envelope письмо почта', 'category' => 'Предметы'],
    ['emoji' => '📧', 'keywords' => 'email почта письмо', 'category' => 'Предметы'],
    ['emoji' => '📌', 'keywords' => 'pin булавка закрепить', 'category' => 'Предметы'],
    // ——— Транспорт и места ———
    ['emoji' => '✈️', 'keywords' => 'plane самолёт полёт', 'category' => 'Транспорт'],
    ['emoji' => '🚗', 'keywords' => 'car машина авто', 'category' => 'Транспорт'],
    ['emoji' => '🏠', 'keywords' => 'house дом', 'category' => 'Транспорт'],
    ['emoji' => '🏢', 'keywords' => 'building офис здание', 'category' => 'Транспорт'],
    ['emoji' => '🌍', 'keywords' => 'earth земля мир глобус', 'category' => 'Транспорт'],
    // ——— Новые сердечки (Unicode 15+) ———
    ['emoji' => '🩷', 'keywords' => 'pink heart розовое сердце', 'category' => 'Сердечки'],
    ['emoji' => '🩵', 'keywords' => 'light blue heart голубое сердце', 'category' => 'Сердечки'],
    ['emoji' => '🩶', 'keywords' => 'grey heart серое сердце', 'category' => 'Сердечки'],
    // ——— Новые лица (Unicode 15–16) ———
    ['emoji' => '🫠', 'keywords' => 'melting face тает растопленный', 'category' => 'Эмоции'],
    ['emoji' => '🫨', 'keywords' => 'shaking face трясётся дрожь', 'category' => 'Эмоции'],
    // ——— Природа (ещё) ———
    ['emoji' => '🌧️', 'keywords' => 'rain дождь', 'category' => 'Природа'],
    ['emoji' => '⛅', 'keywords' => 'cloud sun облачно', 'category' => 'Природа'],
    ['emoji' => '☁️', 'keywords' => 'cloud облако', 'category' => 'Природа'],
    ['emoji' => '🌑', 'keywords' => 'new moon новолуние', 'category' => 'Природа'],
    ['emoji' => '🌒', 'keywords' => 'waxing moon луна', 'category' => 'Природа'],
    ['emoji' => '🌕', 'keywords' => 'full moon полнолуние', 'category' => 'Природа'],
    ['emoji' => '🍁', 'keywords' => 'maple leaf кленовый лист осень', 'category' => 'Природа'],
    ['emoji' => '🌷', 'keywords' => 'tulip тюльпан', 'category' => 'Природа'],
    ['emoji' => '🌼', 'keywords' => 'blossom цветок', 'category' => 'Природа'],
    ['emoji' => '🪷', 'keywords' => 'lotus лотос', 'category' => 'Природа'],
    ['emoji' => '🌾', 'keywords' => 'rice колосья урожай', 'category' => 'Природа'],
    ['emoji' => '🍄', 'keywords' => 'mushroom гриб', 'category' => 'Природа'],
    ['emoji' => '🪨', 'keywords' => 'rock камень', 'category' => 'Природа'],
    // ——— Животные (ещё) ———
    ['emoji' => '🐢', 'keywords' => 'turtle черепаха', 'category' => 'Животные'],
    ['emoji' => '🐍', 'keywords' => 'snake змея', 'category' => 'Животные'],
    ['emoji' => '🦎', 'keywords' => 'lizard ящерица', 'category' => 'Животные'],
    ['emoji' => '🐙', 'keywords' => 'octopus осьминог', 'category' => 'Животные'],
    ['emoji' => '🦑', 'keywords' => 'squid кальмар', 'category' => 'Животные'],
    ['emoji' => '🦀', 'keywords' => 'crab краб', 'category' => 'Животные'],
    ['emoji' => '🐳', 'keywords' => 'whale кит', 'category' => 'Животные'],
    ['emoji' => '🐬', 'keywords' => 'dolphin дельфин', 'category' => 'Животные'],
    ['emoji' => '🦈', 'keywords' => 'shark акула', 'category' => 'Животные'],
    ['emoji' => '🐋', 'keywords' => 'whale кит', 'category' => 'Животные'],
    ['emoji' => '🐟', 'keywords' => 'fish рыба', 'category' => 'Животные'],
    ['emoji' => '🐠', 'keywords' => 'tropical fish рыба', 'category' => 'Животные'],
    ['emoji' => '🦉', 'keywords' => 'owl сова', 'category' => 'Животные'],
    ['emoji' => '🦅', 'keywords' => 'eagle орёл', 'category' => 'Животные'],
    ['emoji' => '🐴', 'keywords' => 'horse лошадь', 'category' => 'Животные'],
    ['emoji' => '🐜', 'keywords' => 'ant муравей', 'category' => 'Животные'],
    ['emoji' => '🦂', 'keywords' => 'scorpion скорпион', 'category' => 'Животные'],
    // ——— Еда и напитки (ещё) ———
    ['emoji' => '🍓', 'keywords' => 'strawberry клубника', 'category' => 'Еда и напитки'],
    ['emoji' => '🍑', 'keywords' => 'peach персик', 'category' => 'Еда и напитки'],
    ['emoji' => '🍒', 'keywords' => 'cherry вишня', 'category' => 'Еда и напитки'],
    ['emoji' => '🥑', 'keywords' => 'avocado авокадо', 'category' => 'Еда и напитки'],
    ['emoji' => '🍌', 'keywords' => 'banana банан', 'category' => 'Еда и напитки'],
    ['emoji' => '🥕', 'keywords' => 'carrot морковь', 'category' => 'Еда и напитки'],
    ['emoji' => '🌽', 'keywords' => 'corn кукуруза', 'category' => 'Еда и напитки'],
    ['emoji' => '🥗', 'keywords' => 'salad салат', 'category' => 'Еда и напитки'],
    ['emoji' => '🍿', 'keywords' => 'popcorn попкорн', 'category' => 'Еда и напитки'],
    ['emoji' => '🍫', 'keywords' => 'chocolate шоколад', 'category' => 'Еда и напитки'],
    ['emoji' => '🍭', 'keywords' => 'lollipop леденец', 'category' => 'Еда и напитки'],
    ['emoji' => '🥐', 'keywords' => 'croissant круассан', 'category' => 'Еда и напитки'],
    ['emoji' => '🧁', 'keywords' => 'cupcake кекс', 'category' => 'Еда и напитки'],
    ['emoji' => '🍵', 'keywords' => 'tea чай', 'category' => 'Еда и напитки'],
    ['emoji' => '🥛', 'keywords' => 'milk молоко', 'category' => 'Еда и напитки'],
    ['emoji' => '🍼', 'keywords' => 'baby bottle бутылочка', 'category' => 'Еда и напитки'],
    ['emoji' => '🍽️', 'keywords' => 'plate dish еда тарелка', 'category' => 'Еда и напитки'],
    // ——— Активность (ещё) ———
    ['emoji' => '🎤', 'keywords' => 'microphone микрофон петь', 'category' => 'Активность'],
    ['emoji' => '🎧', 'keywords' => 'headphones наушники музыка', 'category' => 'Активность'],
    ['emoji' => '🎼', 'keywords' => 'music score ноты музыка', 'category' => 'Активность'],
    ['emoji' => '🎹', 'keywords' => 'piano пианино клавиши', 'category' => 'Активность'],
    ['emoji' => '🥊', 'keywords' => 'boxing бокс', 'category' => 'Активность'],
    ['emoji' => '⚾', 'keywords' => 'baseball бейсбол', 'category' => 'Активность'],
    ['emoji' => '🎳', 'keywords' => 'bowling боулинг', 'category' => 'Активность'],
    ['emoji' => '🎲', 'keywords' => 'dice кубик игра случайность', 'category' => 'Активность'],
    ['emoji' => '🃏', 'keywords' => 'joker карта игра', 'category' => 'Активность'],
    ['emoji' => '🧩', 'keywords' => 'puzzle пазл головоломка', 'category' => 'Активность'],
    ['emoji' => '🎭', 'keywords' => 'theater театр маски', 'category' => 'Активность'],
    ['emoji' => '🎪', 'keywords' => 'circus цирк', 'category' => 'Активность'],
    ['emoji' => '🎨', 'keywords' => 'art искусство рисование', 'category' => 'Активность'],
    ['emoji' => '🖌️', 'keywords' => 'paint brush кисть краски', 'category' => 'Активность'],
    ['emoji' => '📷', 'keywords' => 'camera фото камера', 'category' => 'Активность'],
    ['emoji' => '🎥', 'keywords' => 'video video camera видео', 'category' => 'Активность'],
    ['emoji' => '🎣', 'keywords' => 'fishing рыбалка', 'category' => 'Активность'],
    ['emoji' => '🛷', 'keywords' => 'sled санки зима', 'category' => 'Активность'],
    ['emoji' => '⛷️', 'keywords' => 'skier лыжи', 'category' => 'Активность'],
    // ——— Предметы (ещё) ———
    ['emoji' => '🔍', 'keywords' => 'magnifier поиск лупа', 'category' => 'Предметы'],
    ['emoji' => '✂️', 'keywords' => 'scissors ножницы', 'category' => 'Предметы'],
    ['emoji' => '📎', 'keywords' => 'paperclip скрепка', 'category' => 'Предметы'],
    ['emoji' => '🖊️', 'keywords' => 'pen ручка писать', 'category' => 'Предметы'],
    ['emoji' => '📝', 'keywords' => 'memo заметки запись', 'category' => 'Предметы'],
    ['emoji' => '📚', 'keywords' => 'books книги', 'category' => 'Предметы'],
    ['emoji' => '💰', 'keywords' => 'money bag деньги', 'category' => 'Предметы'],
    ['emoji' => '💵', 'keywords' => 'dollar bill доллар купюра', 'category' => 'Предметы'],
    ['emoji' => '💳', 'keywords' => 'card кредитка карта', 'category' => 'Предметы'],
    ['emoji' => '🛒', 'keywords' => 'shopping cart корзина покупки', 'category' => 'Предметы'],
    ['emoji' => '🛍️', 'keywords' => 'shopping bags покупки пакеты', 'category' => 'Предметы'],
    ['emoji' => '🎒', 'keywords' => 'backpack рюкзак', 'category' => 'Предметы'],
    ['emoji' => '☂️', 'keywords' => 'umbrella зонт дождь', 'category' => 'Предметы'],
    ['emoji' => '🧴', 'keywords' => 'lotion крем косметика', 'category' => 'Предметы'],
    ['emoji' => '🪥', 'keywords' => 'toothbrush зубная щётка', 'category' => 'Предметы'],
    // ——— Транспорт и места (ещё) ———
    ['emoji' => '🚀', 'keywords' => 'rocket ракета космос', 'category' => 'Транспорт'],
    ['emoji' => '🚂', 'keywords' => 'train поезд', 'category' => 'Транспорт'],
    ['emoji' => '🚌', 'keywords' => 'bus автобус', 'category' => 'Транспорт'],
    ['emoji' => '🛵', 'keywords' => 'scooter скутер', 'category' => 'Транспорт'],
    ['emoji' => '🚲', 'keywords' => 'bicycle велосипед', 'category' => 'Транспорт'],
    ['emoji' => '⛵', 'keywords' => 'sailboat парусник лодка', 'category' => 'Транспорт'],
    ['emoji' => '🚁', 'keywords' => 'helicopter вертолёт', 'category' => 'Транспорт'],
    ['emoji' => '🏥', 'keywords' => 'hospital больница', 'category' => 'Транспорт'],
    ['emoji' => '🏫', 'keywords' => 'school школа', 'category' => 'Транспорт'],
    ['emoji' => '🏪', 'keywords' => 'store магазин', 'category' => 'Транспорт'],
    ['emoji' => '🏨', 'keywords' => 'hotel отель', 'category' => 'Транспорт'],
    ['emoji' => '⛪', 'keywords' => 'church церковь', 'category' => 'Транспорт'],
    ['emoji' => '🗼', 'keywords' => 'tower башня', 'category' => 'Транспорт'],
    ['emoji' => '🗽', 'keywords' => 'statue свобода', 'category' => 'Транспорт'],
    ['emoji' => '🏖️', 'keywords' => 'beach пляж море', 'category' => 'Транспорт'],
    // ——— Флаги ———
    ['emoji' => '🇷🇺', 'keywords' => 'russia russian россия русский флаг', 'category' => 'Флаги'],
    ['emoji' => '🇺🇦', 'keywords' => 'ukraine ukrainian украина украинский флаг', 'category' => 'Флаги'],
    ['emoji' => '🇺🇸', 'keywords' => 'usa america american сша америка флаг', 'category' => 'Флаги'],
    ['emoji' => '🇬🇧', 'keywords' => 'uk britain british англия британский флаг', 'category' => 'Флаги'],
    ['emoji' => '🇩🇪', 'keywords' => 'germany german германия немецкий флаг', 'category' => 'Флаги'],
    ['emoji' => '🇫🇷', 'keywords' => 'france french франция французский флаг', 'category' => 'Флаги'],
    ['emoji' => '🇮🇹', 'keywords' => 'italy italian италия итальянский флаг', 'category' => 'Флаги'],
    ['emoji' => '🇪🇸', 'keywords' => 'spain spanish испания испанский флаг', 'category' => 'Флаги'],
    ['emoji' => '🇨🇳', 'keywords' => 'china chinese китай китайский флаг', 'category' => 'Флаги'],
    ['emoji' => '🇯🇵', 'keywords' => 'japan japanese япония японский флаг', 'category' => 'Флаги'],
    ['emoji' => '🇰🇷', 'keywords' => 'korea south korean корея южная флаг', 'category' => 'Флаги'],
    ['emoji' => '🇧🇷', 'keywords' => 'brazil brazilian бразилия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇮🇳', 'keywords' => 'india indian индия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇨🇦', 'keywords' => 'canada canadian канада флаг', 'category' => 'Флаги'],
    ['emoji' => '🇦🇺', 'keywords' => 'australia australian австралия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇵🇱', 'keywords' => 'poland polish польша польский флаг', 'category' => 'Флаги'],
    ['emoji' => '🇷🇸', 'keywords' => 'serbia serbian сербия сербский флаг', 'category' => 'Флаги'],
    ['emoji' => '🇧🇾', 'keywords' => 'belarus belarusian беларусь флаг', 'category' => 'Флаги'],
    ['emoji' => '🇰🇿', 'keywords' => 'kazakhstan kazakh казахстан флаг', 'category' => 'Флаги'],
    ['emoji' => '🇹🇷', 'keywords' => 'turkey turkish турция турецкий флаг', 'category' => 'Флаги'],
    ['emoji' => '🇳🇱', 'keywords' => 'netherlands dutch нидерланды голландия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇸🇪', 'keywords' => 'sweden swedish швеция флаг', 'category' => 'Флаги'],
    ['emoji' => '🇨🇭', 'keywords' => 'switzerland swiss швейцария флаг', 'category' => 'Флаги'],
    ['emoji' => '🇦🇹', 'keywords' => 'austria austrian австрия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇬🇷', 'keywords' => 'greece greek греция флаг', 'category' => 'Флаги'],
    ['emoji' => '🇵🇹', 'keywords' => 'portugal portuguese португалия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇲🇽', 'keywords' => 'mexico mexican мексика флаг', 'category' => 'Флаги'],
    ['emoji' => '🇦🇷', 'keywords' => 'argentina аргентина флаг', 'category' => 'Флаги'],
    ['emoji' => '🇿🇦', 'keywords' => 'south africa юар африка флаг', 'category' => 'Флаги'],
    ['emoji' => '🇮🇱', 'keywords' => 'israel israeli израиль флаг', 'category' => 'Флаги'],
    ['emoji' => '🏳️', 'keywords' => 'white flag белый флаг', 'category' => 'Флаги'],
    ['emoji' => '🏴', 'keywords' => 'black flag чёрный флаг', 'category' => 'Флаги'],
    ['emoji' => '🏳️‍🌈', 'keywords' => 'rainbow flag радужный флаг прайд', 'category' => 'Флаги'],
    // ——— Флаги (дополнительно) ———
    ['emoji' => '🇦🇪', 'keywords' => 'uae emirates оаэ эмираты флаг', 'category' => 'Флаги'],
    ['emoji' => '🇦🇱', 'keywords' => 'albania албания флаг', 'category' => 'Флаги'],
    ['emoji' => '🇦🇲', 'keywords' => 'armenia армения флаг', 'category' => 'Флаги'],
    ['emoji' => '🇦🇿', 'keywords' => 'azerbaijan азербайджан флаг', 'category' => 'Флаги'],
    ['emoji' => '🇧🇪', 'keywords' => 'belgium belgian бельгия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇧🇬', 'keywords' => 'bulgaria болгария флаг', 'category' => 'Флаги'],
    ['emoji' => '🇧🇭', 'keywords' => 'bahrain бахрейн флаг', 'category' => 'Флаги'],
    ['emoji' => '🇭🇷', 'keywords' => 'croatia хорватия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇨🇾', 'keywords' => 'cyprus кипр флаг', 'category' => 'Флаги'],
    ['emoji' => '🇨🇿', 'keywords' => 'czech чехия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇩🇰', 'keywords' => 'denmark danish дания флаг', 'category' => 'Флаги'],
    ['emoji' => '🇪🇪', 'keywords' => 'estonia эстония флаг', 'category' => 'Флаги'],
    ['emoji' => '🇫🇮', 'keywords' => 'finland финляндия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇬🇪', 'keywords' => 'georgia грузия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇭🇺', 'keywords' => 'hungary венгрия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇮🇸', 'keywords' => 'iceland исландия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇮🇪', 'keywords' => 'ireland ирландия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇱🇻', 'keywords' => 'latvia латвия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇱🇹', 'keywords' => 'lithuania литва флаг', 'category' => 'Флаги'],
    ['emoji' => '🇱🇺', 'keywords' => 'luxembourg люксембург флаг', 'category' => 'Флаги'],
    ['emoji' => '🇲🇹', 'keywords' => 'malta мальта флаг', 'category' => 'Флаги'],
    ['emoji' => '🇲🇩', 'keywords' => 'moldova молдова флаг', 'category' => 'Флаги'],
    ['emoji' => '🇲🇪', 'keywords' => 'montenegro черногория флаг', 'category' => 'Флаги'],
    ['emoji' => '🇲🇰', 'keywords' => 'macedonia north македония флаг', 'category' => 'Флаги'],
    ['emoji' => '🇳🇴', 'keywords' => 'norway норвегия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇷🇴', 'keywords' => 'romania румыния флаг', 'category' => 'Флаги'],
    ['emoji' => '🇸🇰', 'keywords' => 'slovakia словакия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇸🇮', 'keywords' => 'slovenia словения флаг', 'category' => 'Флаги'],
    ['emoji' => '🇺🇿', 'keywords' => 'uzbekistan узбекистан флаг', 'category' => 'Флаги'],
    ['emoji' => '🇹🇯', 'keywords' => 'tajikistan таджикистан флаг', 'category' => 'Флаги'],
    ['emoji' => '🇹🇲', 'keywords' => 'turkmenistan туркменистан флаг', 'category' => 'Флаги'],
    ['emoji' => '🇰🇬', 'keywords' => 'kyrgyzstan кыргызстан флаг', 'category' => 'Флаги'],
    ['emoji' => '🇲🇳', 'keywords' => 'mongolia монголия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇻🇳', 'keywords' => 'vietnam вьетнам флаг', 'category' => 'Флаги'],
    ['emoji' => '🇹🇭', 'keywords' => 'thailand таиланд флаг', 'category' => 'Флаги'],
    ['emoji' => '🇮🇩', 'keywords' => 'indonesia индонезия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇲🇾', 'keywords' => 'malaysia малайзия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇸🇬', 'keywords' => 'singapore сингапур флаг', 'category' => 'Флаги'],
    ['emoji' => '🇵🇭', 'keywords' => 'philippines филиппины флаг', 'category' => 'Флаги'],
    ['emoji' => '🇭🇰', 'keywords' => 'hong kong гонконг флаг', 'category' => 'Флаги'],
    ['emoji' => '🇹🇼', 'keywords' => 'taiwan тайвань флаг', 'category' => 'Флаги'],
    ['emoji' => '🇰🇵', 'keywords' => 'north korea кндр корея северная флаг', 'category' => 'Флаги'],
    ['emoji' => '🇪🇬', 'keywords' => 'egypt египет флаг', 'category' => 'Флаги'],
    ['emoji' => '🇳🇬', 'keywords' => 'nigeria нигерия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇰🇪', 'keywords' => 'kenya кения флаг', 'category' => 'Флаги'],
    ['emoji' => '🇬🇭', 'keywords' => 'ghana гана флаг', 'category' => 'Флаги'],
    ['emoji' => '🇪🇹', 'keywords' => 'ethiopia эфиопия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇲🇦', 'keywords' => 'morocco марокко флаг', 'category' => 'Флаги'],
    ['emoji' => '🇹🇳', 'keywords' => 'tunisia тунис флаг', 'category' => 'Флаги'],
    ['emoji' => '🇨🇱', 'keywords' => 'chile чили флаг', 'category' => 'Флаги'],
    ['emoji' => '🇨🇴', 'keywords' => 'colombia колумбия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇵🇪', 'keywords' => 'peru перу флаг', 'category' => 'Флаги'],
    ['emoji' => '🇻🇪', 'keywords' => 'venezuela венесуэла флаг', 'category' => 'Флаги'],
    ['emoji' => '🇪🇨', 'keywords' => 'ecuador эквадор флаг', 'category' => 'Флаги'],
    ['emoji' => '🇨🇺', 'keywords' => 'cuba куба флаг', 'category' => 'Флаги'],
    ['emoji' => '🇯🇲', 'keywords' => 'jamaica ямайка флаг', 'category' => 'Флаги'],
    ['emoji' => '🇳🇿', 'keywords' => 'new zealand новая зеландия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇸🇦', 'keywords' => 'saudi arabia саудия флаг', 'category' => 'Флаги'],
    ['emoji' => '🇮🇷', 'keywords' => 'iran иран флаг', 'category' => 'Флаги'],
    ['emoji' => '🇮🇶', 'keywords' => 'iraq ирак флаг', 'category' => 'Флаги'],
    ['emoji' => '🇵🇰', 'keywords' => 'pakistan пакистан флаг', 'category' => 'Флаги'],
    ['emoji' => '🇧🇩', 'keywords' => 'bangladesh бангладеш флаг', 'category' => 'Флаги'],
    ['emoji' => '🇱🇰', 'keywords' => 'sri lanka шри ланка флаг', 'category' => 'Флаги'],
    ['emoji' => '🇷🇼', 'keywords' => 'rwanda руанда флаг', 'category' => 'Флаги'],
    ['emoji' => '🇺🇬', 'keywords' => 'uganda уганда флаг', 'category' => 'Флаги'],
    ['emoji' => '🇬🇦', 'keywords' => 'gabon габон флаг', 'category' => 'Флаги'],
    ['emoji' => '🇲🇨', 'keywords' => 'monaco монако флаг', 'category' => 'Флаги'],
    ['emoji' => '🇱🇮', 'keywords' => 'liechtenstein лихтенштейн флаг', 'category' => 'Флаги'],
    ['emoji' => '🇸🇲', 'keywords' => 'san marino сан марино флаг', 'category' => 'Флаги'],
    ['emoji' => '🇻🇦', 'keywords' => 'vatican ватикан флаг', 'category' => 'Флаги'],
    // ——— Жесты и человечки (facepalm, shrug и др.) ———
    ['emoji' => '🤷', 'keywords' => 'shrug пожимание плечами не знаю', 'category' => 'Жесты'],
    ['emoji' => '🤷‍♂️', 'keywords' => 'shrug man мужчина плечи', 'category' => 'Жесты'],
    ['emoji' => '🤷‍♀️', 'keywords' => 'shrug woman женщина плечи', 'category' => 'Жесты'],
    ['emoji' => '🤦', 'keywords' => 'facepalm рука лицо стыд', 'category' => 'Жесты'],
    ['emoji' => '🤦‍♂️', 'keywords' => 'facepalm man мужчина стыд', 'category' => 'Жесты'],
    ['emoji' => '🤦‍♀️', 'keywords' => 'facepalm woman женщина стыд', 'category' => 'Жесты'],
    ['emoji' => '🙅', 'keywords' => 'no gesture запрет нет', 'category' => 'Жесты'],
    ['emoji' => '🙅‍♂️', 'keywords' => 'no man мужчина нет', 'category' => 'Жесты'],
    ['emoji' => '🙅‍♀️', 'keywords' => 'no woman женщина нет', 'category' => 'Жесты'],
    ['emoji' => '🙆', 'keywords' => 'ok gesture ок одобрение', 'category' => 'Жесты'],
    ['emoji' => '🙆‍♂️', 'keywords' => 'ok man мужчина ок', 'category' => 'Жесты'],
    ['emoji' => '🙆‍♀️', 'keywords' => 'ok woman женщина ок', 'category' => 'Жесты'],
    ['emoji' => '🙇', 'keywords' => 'bow поклон извинение', 'category' => 'Жесты'],
    ['emoji' => '🙇‍♂️', 'keywords' => 'bow man мужчина поклон', 'category' => 'Жесты'],
    ['emoji' => '🙇‍♀️', 'keywords' => 'bow woman женщина поклон', 'category' => 'Жесты'],
    ['emoji' => '🙋', 'keywords' => 'raise hand рука вверх', 'category' => 'Жесты'],
    ['emoji' => '🙋‍♂️', 'keywords' => 'raise hand man мужчина', 'category' => 'Жесты'],
    ['emoji' => '🙋‍♀️', 'keywords' => 'raise hand woman женщина', 'category' => 'Жесты'],
    ['emoji' => '💆', 'keywords' => 'massage массаж головы', 'category' => 'Жесты'],
    ['emoji' => '💆‍♂️', 'keywords' => 'massage man мужчина', 'category' => 'Жесты'],
    ['emoji' => '💆‍♀️', 'keywords' => 'massage woman женщина', 'category' => 'Жесты'],
    ['emoji' => '🤳', 'keywords' => 'selfie селфи', 'category' => 'Жесты'],
    ['emoji' => '🦾', 'keywords' => 'mechanical arm рука механическая', 'category' => 'Жесты'],
    ['emoji' => '🦿', 'keywords' => 'mechanical leg нога механическая', 'category' => 'Жесты'],
];
